import { themeVariablesStyle, useThemeStore } from './theme';
function fontStack(font) {
    const needsQuote = /\s/.test(font);
    const primary = needsQuote ? `'${font}'` : font;
    return `${primary}, Inter, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif`;
}
export const defaultModalTokens = {
    title: 'Confirmation',
    body: 'Are you sure you want to proceed? This action cannot be undone.',
    openByDefault: false,
    rounded: 'rounded-lg',
    fontFamily: 'Inter',
    primaryColor: '#3b82f6',
};
export function buildModalHtml(t) {
    const ff = fontStack(t.fontFamily);
    const open = !!t.openByDefault;
    return `<section class=\"py-16\"><div class=\"px-6 max-w-4xl mx-auto\" style=\"font-family:${ff}\"><button type=\"button\" class=\"twb-btn twb-btn-solid ${t.rounded}\" data-open-modal style=\"--btn-bg:${t.primaryColor}\">Open modal</button><div class=\"fixed inset-0 ${open ? '' : 'hidden'}\" role=\"dialog\" aria-modal=\"true\" data-modal-root><div class=\"absolute inset-0 bg-black/50\" data-backdrop></div><div class=\"relative z-10 mx-auto mt-24 max-w-lg\"><div class=\"twb-card p-6 ${t.rounded}\"><div class=\"text-lg font-semibold mb-2 text-gray-900 dark:text-white\">${t.title}</div><div class=\"twb-text-muted mb-4\">${t.body}</div><div class=\"flex justify-end gap-3\"><button type=\"button\" class=\"twb-btn twb-btn-outline ${t.rounded}\" data-close-modal style=\"--btn-color:${t.primaryColor}\">Cancel</button><button type=\"button\" class=\"twb-btn twb-btn-solid ${t.rounded}\" style=\"--btn-bg:${t.primaryColor}\" data-confirm>Confirm</button></div></div></div></div></div></section>`;
}
export function generateModalFrameworks(tokens) {
    const theme = useThemeStore();
    const vars = themeVariablesStyle(theme.tokens);
    const fonts = `<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n<link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Poppins:wght@400;500;600;700&family=Roboto:wght@400;500;700&family=Open+Sans:wght@400;600;700&display=swap\" rel=\"stylesheet\">`;
    const style = `<style>${vars}</style>`;
    const ff = fontStack(tokens.fontFamily);
    // Vue
    const vue = `<template>\n  <section class=\"py-16\">\n    <div class=\"px-6 max-w-4xl mx-auto\" style=\"font-family:${ff}\">\n      <button type=\"button\" class=\"twb-btn twb-btn-solid ${tokens.rounded}\" @click=\"open=true\" style=\"--btn-bg:${tokens.primaryColor}\">Open modal</button>\n      <div v-show=\"open\" class=\"fixed inset-0\" role=\"dialog\" aria-modal=\"true\">\n        <div class=\"absolute inset-0 bg-black/50\" @click=\"open=false\"></div>\n        <div class=\"relative z-10 mx-auto mt-24 max-w-lg\">\n          <div class=\"twb-card p-6 ${tokens.rounded}\">\n            <div class=\"text-lg font-semibold mb-2 text-gray-900 dark:text-white\">${tokens.title}</div>\n            <div class=\"twb-text-muted mb-4\">${tokens.body}</div>\n            <div class=\"flex justify-end gap-3\">\n              <button type=\"button\" class=\"twb-btn twb-btn-outline ${tokens.rounded}\" @click=\"open=false\" style=\"--btn-color:${tokens.primaryColor}\">Cancel</button>\n              <button type=\"button\" class=\"twb-btn twb-btn-solid ${tokens.rounded}\" @click=\"open=false\" style=\"--btn-bg:${tokens.primaryColor}\">Confirm</button>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </section>\n</template>\n<script setup lang=\"ts\">\nimport { ref } from 'vue'\nconst open = ref(${!!tokens.openByDefault})\n</script>\n<!-- Include in <head>: -->\n${fonts}\n${style}`;
    // React
    const react = `import { useState } from 'react'\nexport function Modal(){\n  const [open, setOpen] = useState(${!!tokens.openByDefault})\n  return (\n    <section className=\"py-16\">\n      <div className=\"px-6 max-w-4xl mx-auto\" style={{fontFamily:'${ff}'}}>\n        <button type=\"button\" className=\"twb-btn twb-btn-solid ${tokens.rounded}\" onClick={()=> setOpen(true)} style={{'--btn-bg':'${tokens.primaryColor}'} as any}>Open modal</button>\n        {open && (\n          <div className=\"fixed inset-0\" role=\"dialog\" aria-modal=\"true\">\n            <div className=\"absolute inset-0 bg-black/50\" onClick={()=> setOpen(false)}></div>\n            <div className=\"relative z-10 mx-auto mt-24 max-w-lg\">\n              <div className=\"twb-card p-6 ${tokens.rounded}\">\n                <div className=\"text-lg font-semibold mb-2 text-gray-900 dark:text-white\">${tokens.title}</div>\n                <div className=\"twb-text-muted mb-4\">${tokens.body}</div>\n                <div className=\"flex justify-end gap-3\">\n                  <button type=\"button\" className=\"twb-btn twb-btn-outline ${tokens.rounded}\" onClick={()=> setOpen(false)} style={{'--btn-color':'${tokens.primaryColor}'} as any}>Cancel</button>\n                  <button type=\"button\" className=\"twb-btn twb-btn-solid ${tokens.rounded}\" onClick={()=> setOpen(false)} style={{'--btn-bg':'${tokens.primaryColor}'} as any}>Confirm</button>\n                </div>\n              </div>\n            </div>\n          </div>\n        )}\n      </div>\n    </section>\n  )\n}\n// Include in <head>:\n// ${fonts}\n// ${style}`;
    // Svelte
    const svelte = `<svelte:head>\n${fonts}\n${style}\n</svelte:head>\n<script>\n  let open = ${!!tokens.openByDefault}\n</script>\n<section class=\"py-16\">\n  <div class=\"px-6 max-w-4xl mx-auto\" style=\"font-family:${ff}\">\n    <button type=\"button\" class=\"twb-btn twb-btn-solid ${tokens.rounded}\" on:click=\"{()=> open=true}\" style=\"--btn-bg:${tokens.primaryColor}\">Open modal</button>\n    {#if open}\n      <div class=\"fixed inset-0\" role=\"dialog\" aria-modal=\"true\">\n        <div class=\"absolute inset-0 bg-black/50\" on:click=\"{()=> open=false}\"></div>\n        <div class=\"relative z-10 mx-auto mt-24 max-w-lg\">\n          <div class=\"twb-card p-6 ${tokens.rounded}\">\n            <div class=\"text-lg font-semibold mb-2 text-gray-900 dark:text-white\">${tokens.title}</div>\n            <div class=\"twb-text-muted mb-4\">${tokens.body}</div>\n            <div class=\"flex justify-end gap-3\">\n              <button type=\"button\" class=\"twb-btn twb-btn-outline ${tokens.rounded}\" on:click=\"{()=> open=false}\" style=\"--btn-color:${tokens.primaryColor}\">Cancel</button>\n              <button type=\"button\" class=\"twb-btn twb-btn-solid ${tokens.rounded}\" on:click=\"{()=> open=false}\" style=\"--btn-bg:${tokens.primaryColor}\">Confirm</button>\n            </div>\n          </div>\n        </div>\n      </div>\n    {/if}\n  </div>\n</section>`;
    // Angular
    const angular = `import { Component } from '@angular/core';\n\n@Component({\n  selector: 'modal-wrapper',\n  standalone: true,\n  template: \`<section class=\\"py-16\\">\n    <div class=\\"px-6 max-w-4xl mx-auto\\" style=\\"font-family:${ff}\\">\n      <button type=\\"button\\" class=\\"twb-btn twb-btn-solid ${tokens.rounded}\\" (click)=\\"open=true\\" [ngStyle]=\\"{ '--btn-bg': '${tokens.primaryColor}' }\\">Open modal</button>\n      <div class=\\"fixed inset-0\\" role=\\"dialog\\" aria-modal=\\"true\\" *ngIf=\\"open\\">\n        <div class=\\"absolute inset-0 bg-black/50\\" (click)=\\"open=false\\"></div>\n        <div class=\\"relative z-10 mx-auto mt-24 max-w-lg\\">\n          <div class=\\"twb-card p-6 ${tokens.rounded}\\">\n            <div class=\\"text-lg font-semibold mb-2 text-gray-900 dark:text-white\\">${tokens.title}</div>\n            <div class=\\"twb-text-muted mb-4\\">${tokens.body}</div>\n            <div class=\\"flex justify-end gap-3\\">\n              <button type=\\"button\\" class=\\"twb-btn twb-btn-outline ${tokens.rounded}\\" (click)=\\"open=false\\" [ngStyle]=\\"{ '--btn-color': '${tokens.primaryColor}' }\\">Cancel</button>\n              <button type=\\"button\\" class=\\"twb-btn twb-btn-solid ${tokens.rounded}\\" (click)=\\"open=false\\" [ngStyle]=\\"{ '--btn-bg': '${tokens.primaryColor}' }\\">Confirm</button>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </section>\`,\n  styles: [\`${vars}\`]\n})\nexport class ModalComponent {\n  open = ${!!tokens.openByDefault};\n}`;
    // Plain HTML
    const html = `<!doctype html>\n<html>\n<head>\n${fonts}\n${style}\n<script src=\"https://cdn.tailwindcss.com\"><\/script>\n</head>\n<body>\n${buildModalHtml(tokens)}\n<script>\n(function(){\n  var root = document.querySelector('[data-modal-root]');\n  var openBtn = document.querySelector('[data-open-modal]');\n  if(!root || !openBtn) return;\n  function show(){ root.classList.remove('hidden'); }\n  function hide(){ root.classList.add('hidden'); }\n  openBtn.addEventListener('click', show);\n  var backdrop = root.querySelector('[data-backdrop]');\n  var closeBtn = root.querySelector('[data-close-modal]');\n  if(backdrop) backdrop.addEventListener('click', hide);\n  if(closeBtn) closeBtn.addEventListener('click', hide);\n})();\n</script>\n</body>\n</html>`;
    return { vue, react, svelte, angular, html };
}
